// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Este bloque sobrescribe url/directUrl del schema.prisma, así que directUrl
  // tiene que ir aquí también o `migrate deploy` usa el pooler de Neon (P1002).
  datasource: {
    url: process.env["DATABASE_URL"] as string,
    ...(process.env["DIRECT_URL"] && { directUrl: process.env["DIRECT_URL"] }),
  },
});
