ALTER TYPE "TipoNotificacion" ADD VALUE IF NOT EXISTS 'SOLICITUD_MATERIA';
ALTER TYPE "TipoNotificacion" ADD VALUE IF NOT EXISTS 'SOLICITUD_ACEPTADA';
ALTER TYPE "TipoNotificacion" ADD VALUE IF NOT EXISTS 'SOLICITUD_RECHAZADA';
ALTER TYPE "TipoNotificacion" ADD VALUE IF NOT EXISTS 'NUEVA_TAREA';
ALTER TYPE "TipoNotificacion" ADD VALUE IF NOT EXISTS 'CALIFICACION_DISPONIBLE';
ALTER TYPE "TipoNotificacion" ADD VALUE IF NOT EXISTS 'OBSERVACION_DOCENTE';
ALTER TYPE "TipoNotificacion" ADD VALUE IF NOT EXISTS 'ENTREGA_INCORRECTA';
ALTER TYPE "TipoNotificacion" ADD VALUE IF NOT EXISTS 'RECORDATORIO_FECHA_LIMITE';
ALTER TYPE "TipoNotificacion" ADD VALUE IF NOT EXISTS 'ENTREGA_TARDIA';
ALTER TYPE "TipoNotificacion" ADD VALUE IF NOT EXISTS 'ENTREGA_TAREA';
ALTER TYPE "TipoNotificacion" ADD VALUE IF NOT EXISTS 'ENTREGA_TARDIA_DOCENTE';
ALTER TYPE "TipoNotificacion" ADD VALUE IF NOT EXISTS 'ENTREGA_CORREGIDA';
ALTER TYPE "TipoNotificacion" ADD VALUE IF NOT EXISTS 'TAREAS_PENDIENTES_REVISION';
ALTER TYPE "TipoNotificacion" ADD VALUE IF NOT EXISTS 'ASISTENCIA_FUERA_HORARIO';
ALTER TYPE "TipoNotificacion" ADD VALUE IF NOT EXISTS 'NUEVO_USUARIO';
ALTER TYPE "TipoNotificacion" ADD VALUE IF NOT EXISTS 'MATERIA_CREADA';
ALTER TYPE "TipoNotificacion" ADD VALUE IF NOT EXISTS 'REPORTE_DISPONIBLE';
ALTER TYPE "TipoNotificacion" ADD VALUE IF NOT EXISTS 'ALERTA_ADMIN';

CREATE INDEX IF NOT EXISTS "Notificacion_usuarioId_createdAt_idx"
ON "Notificacion"("usuarioId", "createdAt");

CREATE INDEX IF NOT EXISTS "Notificacion_usuarioId_leida_idx"
ON "Notificacion"("usuarioId", "leida");

CREATE INDEX IF NOT EXISTS "Notificacion_usuarioId_tipo_referenciaId_idx"
ON "Notificacion"("usuarioId", "tipo", "referenciaId");
